
<div class="report" style="display:flex">
<table class="data-table data-table-definition-list">
        <thead>
            <tr>
                <th>COOKIE name</th>
                <th>COOKIE Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>CART</th>
                <td>The association with your shopping cart.</td>
            </tr>
            <tr>
                <th>CATEGORY_INFO</th>
                <td>Stores the category info on the page, that allows to display pages more quickly.</td>
            </tr>
            <tr>
                <th>COMPARE</th>
                <td>The items that you have in the Compare Products list.</td>
            </tr>
            <tr>
                <th>CUSTOMER</th>
                <td>An encrypted version of your customer id with the store.</td>
            </tr>
            <tr>
                <th>CUSTOMER_AUTH</th>
                <td>An indicator if you are currently logged into the store.</td>
            </tr>
            <tr>
                <th>CUSTOMER_INFO</th>
                <td>An encrypted version of the customer group you belong to.</td>
            </tr>
            <tr>
                <th>CUSTOMER_SEGMENT_IDS</th>
                <td>Stores the Customer Segment ID</td>
            </tr>
            <tr>
                <th>EXTERNAL_NO_CACHE</th>
                <td>A flag, which indicates whether caching is disabled or not.</td>
            </tr>
            <tr>
                <th>FORM_KEY</th>
                <td>Stores form key used by page cache functionality.</td>
            </tr>
            <tr>
                <th>FRONTEND</th>
                <td>Your session ID on the server.</td>
            </tr>
            <tr>
                <th>GUEST-VIEW</th>
                <td>Allows guests to edit their orders.</td>
            </tr>
            <tr>
                <th>LAST_CATEGORY</th>
                <td>The last category you visited.</td>
            </tr>
            <tr>
                <th>LAST_PRODUCT</th>
                <td>The most recent product you have viewed.</td>
            </tr>
            <tr>
                <th>NEWMESSAGE</th>
                <td>Indicates whether a new message has been received.</td>
            </tr>
            <tr>
                <th>NO_CACHE</th>
                <td>Indicates whether it is allowed to use cache.</td>
            </tr>
            <tr>
                <th>PERSISTENT_SHOPPING_CART</th>
                <td>A link to information about your cart and viewing history if you have asked the site.</td>
            </tr>
            <tr>
                <th>RECENTLYCOMPARED</th>
                <td>The items that you have recently compared.</td>
            </tr>
            <tr>
                <th>STF</th>
                <td>Information on products you have emailed to friends.</td>
            </tr>
            <tr>
                <th>STORE</th>
                <td>The store view or language you have selected.</td>
            </tr>
            <tr>
                <th>USER_ALLOWED_SAVE_COOKIE</th>
                <td>Indicates whether a customer allowed to use cookies.</td>
            </tr>
            <tr>
                <th>VIEWED_PRODUCT_IDS</th>
                <td>The products that you have recently viewed.</td>
            </tr>
            <tr>
                <th>WISHLIST</th>
                <td>An encrypted list of products added to your Wish List.</td>
            </tr>
            <tr>
                <th>WISHLIST_CNT</th>
                <td>The number of items in your Wish List.</td>
            </tr>
        </tbody>
    </table>
    <table class="data-table data-table-definition-list">
        <thead>
            <tr>
                <th>COOKIE name</th>
                <th>COOKIE Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>CART</th>
                <td>The association with your shopping cart.</td>
            </tr>
            <tr>
                <th>CATEGORY_INFO</th>
                <td>Stores the category info on the page, that allows to display pages more quickly.</td>
            </tr>
            <tr>
                <th>COMPARE</th>
                <td>The items that you have in the Compare Products list.</td>
            </tr>
            <tr>
                <th>CUSTOMER</th>
                <td>An encrypted version of your customer id with the store.</td>
            </tr>
            <tr>
                <th>CUSTOMER_AUTH</th>
                <td>An indicator if you are currently logged into the store.</td>
            </tr>
            <tr>
                <th>CUSTOMER_INFO</th>
                <td>An encrypted version of the customer group you belong to.</td>
            </tr>
            <tr>
                <th>CUSTOMER_SEGMENT_IDS</th>
                <td>Stores the Customer Segment ID</td>
            </tr>
            <tr>
                <th>EXTERNAL_NO_CACHE</th>
                <td>A flag, which indicates whether caching is disabled or not.</td>
            </tr>
            <tr>
                <th>FORM_KEY</th>
                <td>Stores form key used by page cache functionality.</td>
            </tr>
            <tr>
                <th>FRONTEND</th>
                <td>Your session ID on the server.</td>
            </tr>
            <tr>
                <th>GUEST-VIEW</th>
                <td>Allows guests to edit their orders.</td>
            </tr>
            <tr>
                <th>LAST_CATEGORY</th>
                <td>The last category you visited.</td>
            </tr>
            <tr>
                <th>LAST_PRODUCT</th>
                <td>The most recent product you have viewed.</td>
            </tr>
            <tr>
                <th>NEWMESSAGE</th>
                <td>Indicates whether a new message has been received.</td>
            </tr>
            <tr>
                <th>NO_CACHE</th>
                <td>Indicates whether it is allowed to use cache.</td>
            </tr>
            <tr>
                <th>PERSISTENT_SHOPPING_CART</th>
                <td>A link to information about your cart and viewing history if you have asked the site.</td>
            </tr>
            <tr>
                <th>RECENTLYCOMPARED</th>
                <td>The items that you have recently compared.</td>
            </tr>
            <tr>
                <th>STF</th>
                <td>Information on products you have emailed to friends.</td>
            </tr>
            <tr>
                <th>STORE</th>
                <td>The store view or language you have selected.</td>
            </tr>
            <tr>
                <th>USER_ALLOWED_SAVE_COOKIE</th>
                <td>Indicates whether a customer allowed to use cookies.</td>
            </tr>
            <tr>
                <th>VIEWED_PRODUCT_IDS</th>
                <td>The products that you have recently viewed.</td>
            </tr>
            <tr>
                <th>WISHLIST</th>
                <td>An encrypted list of products added to your Wish List.</td>
            </tr>
            <tr>
                <th>WISHLIST_CNT</th>
                <td>The number of items in your Wish List.</td>
            </tr>
        </tbody>
    </table>


</div>